### ISSUE TITLE
(PDF Downloading) Copyright Notice treated as dropdown menu category

### ISSUE THREAD

**Issue by AaronBenDaniel** [TheOnlyWayUp/WattpadDownloader#36]
The copyright notice acts as a dropdown menu for the book info and table of contents.

![image](https://github.com/user-attachments/assets/8d4e4844-5685-4f5c-b7e7-20c3208baa03)

**Comment by TheOnlyWayUp** [comment]
Oh that's interesting, I think this is because the ToC title is a `h2`, so it becomes a subtitle, same for the book title

https://github.com/TheOnlyWayUp/WattpadDownloader/blob/f8ab31821027e121a45339b401ef3fde9e73e3c9/src/api/src/pdf/book.html#L13-L16

https://github.com/TheOnlyWayUp/WattpadDownloader/blob/f8ab31821027e121a45339b401ef3fde9e73e3c9/src/api/src/create_book.py#L693

**Comment by TheOnlyWayUp** [comment]
Fixed!
